### ISSUE TITLE
Give Users a way to signup with our app

### ISSUE THREAD

**Issue by dougwoodrow** [tampabaylaravel/meetup#1]
**Describe the problem.**
Users should be able to signup with our application via various methods.

**Describe the solution you'd like.**
We need a way to allow users to authenticate with the app. Authentication via Laravel Socialite would be preferable implementation. This should include authentication for the following methods:

- Twitter
- GitHub
- Bitbucket
- GitLab

No email authentication should be needed at this time since all developers have either a GitHub, Bitbucket, or GitLab account. This greatly simplifies the need for setting up User Accounts manually.

**Comment by FatBoyXPC** [comment]
For MVP I'm going to allow email signup for now
