### ISSUE TITLE
Setup env file checker

### ISSUE THREAD

**Issue by FatBoyXPC** [tampabaylaravel/meetup#10]
There's a package that compares a local `.env` to `.env.example` to ensure we make the appropriate changes in these files when committing or pulling. Let's set that up, and maybe even offer git hooks.

Options:

https://github.com/JulienTant/Laravel-Env-Sync
https://github.com/baopham/env-checker

**Comment by david-fairbanks42** [comment]
I love this idea. Laravel-Env-Sync seems more up to date and maintained.

**Comment by FatBoyXPC** [comment]
Yep, that's what I chose! If you want to review that PR that would be dope!
