### ISSUE TITLE
Give Users a way to create Meetings

### ISSUE THREAD

**Issue by dougwoodrow** [tampabaylaravel/meetup#2]
**Describe the problem.**
Users need to be able to create Events.

**Describe the solution you'd like.**

- `name` - String
- `location` - GeoPoints or Google Place ID
- `startTime` - DateTime
- `endTime` - DateTime
- `createdAt` - DateTime
- `updatedAt` - DateTime
- `attending` - Users[]
- `createdBy` - User

**Comment by david-fairbanks42** [comment]
An API endpoints exists to create, update and delete meetings. Since roles have not been created yet, any authenticated user can create a meeting. After it's created only that user can update or delete it.
POST `api/meeting`
```
{
  name: (string),
  description: (string),
  location: (string),
  start_time: (date_time),
  end_time: (date_time)
}
```

**Comment by FatBoyXPC** [comment]
Should we get some OpenAPI documentation going for this? :thinking:

**Comment by david-fairbanks42** [comment]
My vote is yes. I'm also conflicted about `api/meeting` vs `api/meetings`.

**Comment by FatBoyXPC** [comment]
Oh, wow. I totally missed that. Can you send in a PR to pluralize the routes? That's fairly standard these days.

**Comment by david-fairbanks42** [comment]
Yes, sure can.

**Comment by FatBoyXPC** [comment]
@dougwoodrow should we have a separate ticket for the frontend version of this since the api endpoint is done?

**Comment by dougwoodrow** [comment]
@FatBoyXPC when I created the ticket, I was making the assumption that we would complete the ticket with the front and back in tandem at the same Hackathon. However, if we are going to pipeline them separately, I would untag this as a frontend task and make another ticket. However, keep in mind, the other tickets will also need to be duplicated over to have a frontend ticket as well.

**Comment by FatBoyXPC** [comment]
Sounds good to me. I'll close this for now and if I can remember tonight I'll open tickets for the others.
