### ISSUE TITLE
Events should be queryable

### ISSUE THREAD

**Issue by dougwoodrow** [tampabaylaravel/meetup#3]
**Describe the problem.**
In order to grab Events on the front end, we need some way to query those Events.

**Describe the solution you'd like.**
API Route / GraphQL query that returns:

- `name` - String
- `location` - GeoPoints or Google Place ID
- `startTime` - DateTime
- `endTime` - DateTime
- `createdAt` - DateTime
- `updatedAt` - DateTime
- `attending` - Users[]
- `createdBy` - User

**Comment by david-fairbanks42** [comment]
An API endpoint exists to search for meetings. Search parameters are:

- `name` Full or partial meeting name
- `start_time` Exact start date
- `location` Exact location

GET `api/meeting`

We'll need loosen the start date and location parameters to be useful.

**Comment by FatBoyXPC** [comment]
Closing this one since the endpoint is finished!
