### ISSUE TITLE
Configure User Model

### ISSUE THREAD

**Issue by dougwoodrow** [tampabaylaravel/meetup#5]
**Describe the problem.**
Our app needs Users that can access the information in the application with the following fields and relationships.

**Describe the solution you'd like.**
API Route / GraphQL query that returns:

**Properties**
- `name` - String
- `email` - String, Unique
- `attending` - Events[]

**Comment by FatBoyXPC** [comment]
Note: the `User` model has a `reservations` relationship in place of `attending`.
