### ISSUE TITLE
Event page

### ISSUE THREAD

**Issue by FatBoyXPC** [tampabaylaravel/meetup#7]
**Describe the problem.**
People need to see a way an event's details

**Describe the solution you'd like.**
A url such as `api/meetings/1` is available and displays meeting information.

- Name of the Event
- Start Time of the Event
- Description of the event
- Location Name of the Event's set location

**Comment by david-fairbanks42** [comment]
An API endpoint exists to get a single meetings information.

GET `api/meeting/{meeting_id}`

Returns:
```
{
  success: (boolean),
  meetings: [
    {
      id: (int), 
      name: (string),
      description: (string),
      location: (string),
      start_time: (date_time),
      end_time: (date_time)
  ]
}
```

**Comment by FatBoyXPC** [comment]
Closing this since it's a backend ticket and you did this for us!
