### ISSUE TITLE
User can join an event

### ISSUE THREAD

**Issue by FatBoyXPC** [tampabaylaravel/meetup#8]
**Describe the problem.**
Users need a way to join an event

**Describe the solution you'd like.**
A POST request to a URL such as `api/meetings/1/attend`

- Authenticated user is needed

**Comment by david-fairbanks42** [comment]
I've refactored attendance records from a meeting pivot to it's own model in the branch [attend-from-pivot-to-model](https://github.com/tampabaylaravel/meetup/tree/attend-from-pivot-to-model). If this refactor is approved, there are endpoints for meetings and attend included. The endpoints were required so I could verify the functionality with unit and feature testing.

**Comment by FatBoyXPC** [comment]
@david-fairbanks42 I believe this is also done, right?

**Comment by david-fairbanks42** [comment]
Yes. I was going to leave a comment about the basics of it.

**Comment by FatBoyXPC** [comment]
I'll close it then. Feel free to leave a comment after it's closed if you feel it's necessary! We have tests that support this at the very least :smile:

**Comment by david-fairbanks42** [comment]
An API endpoint exists state if they are attending a meeting.

POST `api/meetings/{meeting_id}/reservations`

The authenticated user making the request is the user that is affected.

Update an attending status with:

PUT `api/meetings/{meeting_id}/reservations`
with data `{attending: (string)}`
Accepted values are `yes`, `no`, `maybe`

Alternatively, using the delete method will set the users attending state to `no`.

DELETE `api/`meetings/{meeting_id}/reservations`
